### ISSUE TITLE
Request for Source Code Access

### ISSUE THREAD

**Issue by ChambersXDU** [YichenLi00/SCLogger#1]
I'm interested in your work presented in the paper `Go Static: Contextualized Logging Statement Generation`, and I found the concepts and results presented in your paper quite inspiring and **would like to replicate your study** to further my understanding. 

Howerver I noticed this repository currently does not include the source code.😹 I understand that managing and releasing code can be time-consuming, but if it is possible, could you please make the source code available? 🤗

Best wishes!

**Comment by YichenLi00** [comment]
Sorry for my late.

I will upload all the code before the FSE conference. Sorry to keep you waiting.

**Comment by ChambersXDU** [comment]
@YichenLi00 
I find a [repo](https://github.com/anonymoussee/Logger) matching your paper, I reckon that may be the early version of your work. I try to run it but failed with some problems, so I have to ask again if you might be able to share the latest code (or giving more details of how to run it).

Respect the effort it takes, thanks again.❤️

**Comment by YichenLi00** [comment]
Yeah, the repo you provided almost contains all the functions outlined in the paper. I haven't yet implemented a user-friendly interface for it. You can proceed with using the code from the repository for now. Once I survive the upcoming deadline, I will work on refining the interface.
