### ISSUE TITLE
Inquiry Regarding Static Analysis Tools Used in SCLogger

### ISSUE THREAD

**Issue by qlbdsc** [YichenLi00/SCLogger#2]
I recently had the privilege of reviewing your paper Go Static: Contextualized Logging Statement Generation and found it to be highly insightful and valuable.
While attempting to reproduce SCLogger, I encountered an issue where the call graph file generated by the static analysis tool I am using could not be parsed by your code. Could you kindly let me know which static analysis tool you used in your experiment? It would be immensely helpful in resolving this issue.
I would greatly appreciate any assistance you can provide.

**Comment by YichenLi00** [comment]
Thank you for your interest! I use javacg(2) to generate the corresponding call graph.

**Comment by qlbdsc** [comment]
Thanks for your reply.
